
FROM tomcat:11.0-jdk25

# Remove default apps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy WAR file into Tomcat
COPY C:\Users\testnaveen\Tomcat\actions-runner\_work\HelloServletApp\HelloServletApp\target\*.war /usr/local/tomcat/webapps/ROOT.war

# Expose port
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]