package com.naveen.servlet;

import java.io.IOException;
import java.io.PrintWriter;

import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

public class HelloServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request,
                         HttpServletResponse response)
            throws ServletException, IOException {

        response.setContentType("text/html");

        PrintWriter out = response.getWriter();

        out.println("<html>");
        out.println("<head><title>Hello Servlet</title></head>");
        out.println("<body>");
        out.println("<h1>Welcome to Java Servlet!</h1>");
        out.println("<h2>Hello Satish, This build is done and applied using Github actions on self-hosted gitactions server - forth try </h2>");
        out.println("<p>This page is generated by a Java Servlet running on Tomcat.</p>");
        out.println("</body>");
        out.println("</html>");
    }
}