name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: [self-hosted, windows]

    env:
      MAVEN_HOME: 'C:\Users\testnaveen\Tomcat\apache-maven-3.9.16'
      JAVA_HOME: 'C:\Program Files\Java\jdk-25.0.3'

      ACR_URL: naveendevopshub.azurecr.io
      IMAGE_NAME: hello-servlet-app
      IMAGE_TAG: latest

      ACR_USER: naveendevopshub
      ACR_PASSWORD: CtsUq5ZvQp5bF64MZS9LLe2YODqY3P7kRa9dCUMY6bXcXNut7xxTJQQJ99CGAC77bzfEqg7NAAACAZCR6Yww

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build WAR using Maven
        shell: powershell
        run: |
          & "$env:MAVEN_HOME\bin\mvn.cmd" clean package -DskipTests

      - name: Verify Files
        shell: powershell
        run: |
          dir
          dir target
          if (!(Test-Path ".\Dockerfile")) { throw "Dockerfile not found" }
          if (!(Get-ChildItem ".\target\*.war")) { throw "WAR file not found" }

      - name: Build Docker Image
        shell: powershell
        run: |
          docker build -t "$env:IMAGE_NAME:$env:IMAGE_TAG" .

      - name: Login to Azure Container Registry
        shell: powershell
        run: |
          $env:ACR_PASSWORD | docker login $env:ACR_URL -u $env:ACR_USER --password-stdin

      - name: Tag Docker Image for ACR
        shell: powershell
        run: |
          docker tag "$env:IMAGE_NAME:$env:IMAGE_TAG" "$env:ACR_URL/$env:IMAGE_NAME:$env:IMAGE_TAG"

      - name: Push Docker Image to ACR
        shell: powershell
        run: |
          docker push "$env:ACR_URL/$env:IMAGE_NAME:$env:IMAGE_TAG"

      - name: Success Message
        shell: powershell
        run: |
          echo "Image pushed to $env:ACR_URL/$env:IMAGE_NAME:$env:IMAGE_TAG"