name: Build & Push Docker Image to Artifactory

on:
  push:
    branches:
      - main

jobs:
  build-and-dockerize:
    runs-on: [self-hosted, windows]

    env:
      MAVEN_HOME: 'C:\Users\testnaveen\Tomcat\apache-maven-3.9.16'
      JAVA_HOME: 'C:\Program Files\Java\jdk-25.0.3'

      DOCKER_IMAGE: naveen-hello-servlet
      DOCKER_TAG: latest

      ARTIFACTORY_URL: naveendevopshub.azurecr.io
      ARTIFACTORY_REPO: docker-local-HelloServletApp
      ARTIFACTORY_USER: naveendevopshub
      ARTIFACTORY_PASSWORD: BAIOWVEgEkQzqTushnRFFb5zt69YovVcSIXvTW6WD8RN6P4ptVMEJQQJ99CGAC77bzfEqg7NAAACAZCRNJEa

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build WAR using Maven
        shell: powershell
        run: |
          & "$env:MAVEN_HOME\bin\mvn.cmd" clean package -DskipTests

      - name: Build Docker Image
        shell: powershell
        run: |
          docker build -t $env:DOCKER_IMAGE:$env:DOCKER_TAG .

      - name: Login to Artifactory Docker Registry
        shell: powershell
        run: |
          echo $env:ARTIFACTORY_PASSWORD | docker login $env:ARTIFACTORY_URL `
            -u $env:ARTIFACTORY_USER --password-stdin

      - name: Tag Docker Image for Artifactory
        shell: powershell
        run: |
          docker tag $env:DOCKER_IMAGE:$env:DOCKER_TAG `
          $env:ARTIFACTORY_URL/$env:ARTIFACTORY_REPO/$env:DOCKER_IMAGE:$env:DOCKER_TAG

      - name: Push Docker Image
        shell: powershell
        run: |
          docker push $env:ARTIFACTORY_URL/$env:ARTIFACTORY_REPO/$env:DOCKER_IMAGE:$env:DOCKER_TAG

      - name: Deployment Info
        run: echo "Image pushed to Artifactory successfully!"