name: Build & Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-dockerize:
    runs-on: [self-hosted, windows]

    env:
      MAVEN_HOME: 'C:\Users\testnaveen\Tomcat\apache-maven-3.9.16'
      JAVA_HOME: 'C:\Program Files\Java\jdk-25.0.3'

      DOCKER_IMAGE: naveen-hello-servlet
      DOCKER_TAG: latest

      ACR_URL: naveendevopshub.azurecr.io
      ACR_REPO: docker-local-helloservletapp
      ACR_USER: ${{ secrets.ACR_USER }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build WAR using Maven
        shell: powershell
        run: |
          & "$env:MAVEN_HOME\bin\mvn.cmd" clean package -DskipTests

      - name: Verify Dockerfile and WAR
        shell: powershell
        run: |
          dir
          dir target
          if (!(Test-Path ".\Dockerfile")) { throw "Dockerfile not found in repo root" }
          if (!(Get-ChildItem ".\target\*.war")) { throw "WAR file not found in target folder" }

      - name: Build Docker Image
        shell: powershell
        run: |
          docker build -t $env:DOCKER_IMAGE:$env:DOCKER_TAG .

      - name: Login to Azure Container Registry
        shell: powershell
        run: |
          $env:ACR_PASSWORD | docker login $env:ACR_URL -u $env:ACR_USER --password-stdin

      - name: Tag Docker Image for ACR
        shell: powershell
        run: |
          docker tag $env:DOCKER_IMAGE:$env:DOCKER_TAG "$env:ACR_URL/$env:ACR_REPO/$env:DOCKER_IMAGE:$env:DOCKER_TAG"

      - name: Push Docker Image to ACR
        shell: powershell
        run: |
          docker push "$env:ACR_URL/$env:ACR_REPO/$env:DOCKER_IMAGE:$env:DOCKER_TAG"

      - name: Deployment Info
        shell: powershell
        run: |
          echo "Image pushed successfully to $env:ACR_URL/$env:ACR_REPO/$env:DOCKER_IMAGE:$env:DOCKER_TAG"